### ISSUE TITLE
A few chapters won't download.

### ISSUE THREAD

**Issue by laughingclouds** [laughingclouds/Scrapia-World#1]
Well, as the title says...they won't...it's because the internal count of the code will get messed up if you change to a different chapter during the sleep time. This can be a pain, because then you will have to first run the whole code for that particular "missing" chapter and then close it to then again make better changes in the database.

**Comment by r3a10god** [comment]
This will be fixed in later releases.

**Comment by laughingclouds** [comment]
This will be fixed in later releases. I'll close this issue when that happens, while informing here what version the enhancement has been on.

**Comment by laughingclouds** [comment]
I guess I'll drop this project in favor of something else. Maybe I'll pick up once python gets more efficient and fast. Anyways, it was nice working with it. I got to learn a lot. I probably won't archive my repo. Closing now.
